[package]
name = "simple-calories-counter"
version = "1.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
rusqlite = "0.37.0"
time = { version = "0.3.41", features = ["local-offset", "formatting", "parsing"] }
