name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Build Windows
      run: cargo build --release --target x86_64-pc-windows-gnu

    - name: Build Linux
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Build Mac
      run: cargo build --release --target x86_64-apple-darwin

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }}-binary
        path: target/release/simple-calories-counter
